### ISSUE TITLE
Operations that change non-concurrent collections must have exclusive access

### ISSUE THREAD

**Issue by samxxxxx** [marcoCasamento/Hangfire.Redis.StackExchange#121]
hello，我有大概6个作业，开始一段时间没有问题，但在运行一段时间后（大约1小时后），会出现如下异常，请问这个我应该怎么解决?

> WARN  2023-05-01 13:06:26,929 [er #1] Hangfire.Server.RecurringJobScheduler - Recurring job 'xxxxxx' can not be scheduled due to an exception.
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.HashSet`1.Contains(T item)
   at Hangfire.Redis.RedisLock.Acquire(IDatabase redis, RedisKey key, TimeSpan timeOut, TimeSpan holdDuration)
   at Hangfire.Redis.RedisLock.Acquire(IDatabase redis, RedisKey key, TimeSpan timeOut)
   at Hangfire.Redis.RedisConnection.AcquireDistributedLock(String resource, TimeSpan timeout)
   at Hangfire.RecurringJobExtensions.AcquireDistributedRecurringJobLock(IStorageConnection connection, String recurringJobId, TimeSpan timeout)
   at Hangfire.Server.RecurringJobScheduler.EnqueueBackgroundJob(BackgroundProcessContext context, IStorageConnection connection, String recurringJobId, DateTime now)
   at Hangfire.Server.RecurringJobScheduler.TryEnqueueBackgroundJob(BackgroundProcessContext context, IStorageConnection connection, String recurringJobId, DateTime now)

根据异常提示，找到代码应该是在这里出现的异常`Hangfire.Redis.StackExchange.RedisLock`类
```c#
internal static IDisposable Acquire([NotNull] IDatabase redis, RedisKey key, TimeSpan timeOut, TimeSpan holdDuration)
{
    if (redis == null)
        throw new ArgumentNullException(nameof(redis));

    if (HeldLocks.ContainsKey(key))
    {
        // lock is already held
        return new RedisLock(redis, key, false, holdDuration);
    }

    // The comparison below uses timeOut as a max timeSpan in waiting Lock
    var i = 0;
    var lockExpirationTime = DateTime.UtcNow + timeOut;
    do
    {
        if (redis.LockTake(key, OwnerId, holdDuration))
        {
            // we have successfully acquired the lock
            return new RedisLock(redis, key, true, holdDuration);
        }
        
        SleepBackOffMultiplier(i++, (int)(lockExpirationTime - DateTime.UtcNow).TotalMilliseconds);
    }
    while (DateTime.UtcNow < lockExpirationTime);

    throw new DistributedLockTimeoutException($"Failed to acquire lock on {key} within given timeout ({timeOut})");
}
```

**Comment by samxxxxx** [comment]
兄弟们1.8.1解决了这个问题
