### ISSUE TITLE
BUG: Can't schedule a job without specifying the queue

### ISSUE THREAD

**Issue by Lexy2** [marcoCasamento/Hangfire.Redis.StackExchange#148]
If you use the overload without the queue to schedule a job, like, `BackgroundJob.Enqueue(() => Console.WriteLine());` Hangfire.Redis.StackExchange fails to enqueue the job with the following exception

```
Unhandled exception. Hangfire.BackgroundJobClientException: Background job creation failed. See inner exception for details.
 ---> System.ArgumentException: A null value is not valid in this context
   at StackExchange.Redis.RedisValue.AssertNotNull() in /_/src/StackExchange.Redis/RedisValue.cs:line 308
   at StackExchange.Redis.Message.CommandKeyValuesMessage..ctor(Int32 db, CommandFlags flags, RedisCommand command, RedisKey& key, RedisValue[] values) in /_/src/StackExchange.Redis/Message.cs:line 1050
   at StackExchange.Redis.Message.Create(Int32 db, CommandFlags flags, RedisCommand command, RedisKey& key, RedisValue[] values) in /_/src/StackExchange.Redis/Message.cs:line 426
   at StackExchange.Redis.RedisDatabase.GetHashSetMessage(RedisKey key, HashEntry[] hashFields, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 3422
   at StackExchange.Redis.RedisDatabase.HashSetAsync(RedisKey key, HashEntry[] hashFields, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 589
   at Hangfire.Redis.StackExchange.RedisConnection.CreateExpiredJob(Job job, IDictionary`2 parameters, DateTime createdAt, TimeSpan expireIn) in C:\Users\lexy.zhitenev\src\repos\Hangfire.Redis.StackExchange\Hangfire.Redis.StackExchange\RedisConnection.cs:line 165
   at Hangfire.Client.CoreBackgroundJobFactory.<>c__DisplayClass15_0.<CreateBackgroundJobTwoSteps>b__0(Int32 _) in C:\projects\hangfire-525\src\Hangfire.Core\Client\CoreBackgroundJobFactory.cs:line 87
```

**Comment by Lexy2** [comment]
Repro:

```csharp
using Hangfire;
using Hangfire.Redis.StackExchange;

GlobalConfiguration.Configuration.UseRedisStorage();

Task.Run(() =>
{
    using (new BackgroundJobServer())
    {
        Console.ReadLine();
    }
});

BackgroundJob.Enqueue(() => Console.WriteLine());
Console.ReadLine();
