### ISSUE TITLE
Execution Worker is in the Failed state now due to an exception, execution will be retried no more than in 00:00:04

### ISSUE THREAD

**Issue by sampsonye** [marcoCasamento/Hangfire.Redis.StackExchange#89]
```
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
at System.Collections.Generic.HashSet`1.Contains(System.Collections.Generic.T item)
at Hangfire.Redis.RedisLock.Acquire(StackExchange.Redis.IDatabase redis, StackExchange.Redis.RedisKey key, System.TimeSpan timeOut, System.TimeSpan holdDuration)
at Hangfire.Redis.RedisLock.Acquire(StackExchange.Redis.IDatabase redis, StackExchange.Redis.RedisKey key, System.TimeSpan timeOut)
at Hangfire.Redis.RedisConnection.AcquireDistributedLock(System.String resource, System.TimeSpan timeout)
at Hangfire.Storage.StorageConnectionExtensions.AcquireDistributedJobLock(Hangfire.Storage.IStorageConnection connection, System.String jobId, System.TimeSpan timeout) at offset 28
at Hangfire.States.BackgroundJobStateChanger.ChangeState(Hangfire.States.StateChangeContext context)
at Hangfire.Server.Worker.TryChangeState(Hangfire.Server.BackgroundProcessContext context, Hangfire.Storage.IStorageConnection connection, Hangfire.Storage.IFetchedJob fetchedJob, Hangfire.States.IState state, System.String[] expectedStates, System.Threading.CancellationToken initializeToken, System.Threading.CancellationToken abortToken) at offset 258
at Hangfire.Server.Worker.Execute(Hangfire.Server.BackgroundProcessContext context)
at Hangfire.Server.BackgroundProcessDispatcherBuilder.ExecuteProcess(System.Guid executionId, System.Object state) at offset 123
at Hangfire.Processing.BackgroundExecution.Run(System.Action`2 callback, System.Object state) at offset 69
```

**Comment by oguzhantopcu** [comment]
I got this error every minute.

**Comment by marcoCasamento** [comment]
Hi, I'm planning to look at this (and others), how to repro ? hangfire ver ?

**Comment by oguzhantopcu** [comment]
I got this every minute, I have no idea why this is happenin.

[14:11:15 ERR]  - Hangfire.Processing.BackgroundExecution -  - - : Execution FetchedJobsWatcher is in the Failed state now due to an exception, execution will be retried no more than in 00:00:04
Hangfire.Storage.DistributedLockTimeoutException: Timeout expired. The timeout elapsed prior to obtaining a distributed lock on the 'Failed to acquire lock on {hangfire}:queue:default:dequeued:lock within given timeout (00:01:00)' resource.
   at Hangfire.Redis.RedisLock.Acquire(IDatabase redis, RedisKey key, TimeSpan timeOut, TimeSpan holdDuration)
   at Hangfire.Redis.RedisLock.Acquire(IDatabase redis, RedisKey key, TimeSpan timeOut)
   at Hangfire.Redis.FetchedJobsWatcher.ProcessQueue(String queue, RedisConnection connection)
   at Hangfire.Redis.FetchedJobsWatcher.Execute(CancellationToken cancellationToken)
   at Hangfire.Processing.BackgroundExecution.Run(Action`2 callback, Object state)

**Comment by oguzhantopcu** [comment]
My app is running on $160 digitalocean droplet that has 8 nonshared cores. Simple dashboard page opening in 15 seconds, sometimes it takes a minute.

![image](https://user-images.githubusercontent.com/2956166/70536928-b1b5f300-1b70-11ea-90da-ece43d422092.png)
