### ISSUE TITLE
 Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.

### ISSUE THREAD

**Issue by xingyunauthor** [marcoCasamento/Hangfire.Redis.StackExchange#90]
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.HashSet`1.Contains(T item)
   at Hangfire.Redis.RedisLock.Acquire(IDatabase redis, RedisKey key, TimeSpan timeOut, TimeSpan holdDuration)
   at Hangfire.Redis.RedisLock.Acquire(IDatabase redis, RedisKey key, TimeSpan timeOut)
   at Hangfire.Redis.RedisConnection.AcquireDistributedLock(String resource, TimeSpan timeout)
   at Hangfire.RecurringJobExtensions.AcquireDistributedRecurringJobLock(IStorageConnection connection, String recurringJobId, TimeSpan timeout)
   at Hangfire.Server.RecurringJobScheduler.EnqueueBackgroundJob(BackgroundProcessContext context, IStorageConnection connection, String recurringJobId, DateTime now)
   at Hangfire.Server.RecurringJobScheduler.TryEnqueueBackgroundJob(BackgroundProcessContext context, IStorageConnection connection, String recurringJobId, DateTime now)

**Comment by xingyunauthor** [comment]
I changed the code to `private static ConcurrentDictionary<RedisKey, RedisKey> HeldLocks => new ConcurrentDictionary<RedisKey, RedisKey>();` 20 days ago, maybe solved this problem, and now not show this bug again

**Comment by gianct79** [comment]
What about controlling access to HeldLocks instance? I added a sync object to the class and acquired that lock on HeldLocks.Add, HeldLocks.Contains and HeldLocks.Remove calls.

```C#
55 private static object _lock = new object();        
56 private static AsyncLocal<ISet<RedisKey>> _heldLocks = new AsyncLocal<ISet<RedisKey>>();
...
83 lock (_lock)
84 {
85     HeldLocks.Add(_key);
86 }
```

Similarly, do the same on Dispose and Acquire methods.
